// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

// Immutable compliance audit trail — never UPDATE/DELETE.
type AuditLog struct {
	ID             int64              `json:"id"`
	OrganizationID pgtype.Int8        `json:"organization_id"`
	ActorID        pgtype.Int8        `json:"actor_id"`
	ActorLogin     pgtype.Text        `json:"actor_login"`
	Action         string             `json:"action"`
	ResourceType   pgtype.Text        `json:"resource_type"`
	ResourceID     pgtype.Int8        `json:"resource_id"`
	Metadata       []byte             `json:"metadata"`
	IpAddress      *netip.Addr        `json:"ip_address"`
	UserAgent      pgtype.Text        `json:"user_agent"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

// Commits associated with pull requests.
type Commit struct {
	ID             int64              `json:"id"`
	Sha            string             `json:"sha"`
	RepositoryID   int64              `json:"repository_id"`
	PullRequestID  pgtype.Int8        `json:"pull_request_id"`
	AuthorID       pgtype.Int8        `json:"author_id"`
	AuthorLogin    string             `json:"author_login"`
	CommitterLogin pgtype.Text        `json:"committer_login"`
	Message        string             `json:"message"`
	CommittedAt    pgtype.Timestamptz `json:"committed_at"`
	Additions      int32              `json:"additions"`
	Deletions      int32              `json:"deletions"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

// GitHub users who interact with monitored repositories. The expertise_vector powers the RAG pipeline for personalized AI code reviews.
type Developer struct {
	ID          int64       `json:"id"`
	GithubID    int64       `json:"github_id"`
	Login       string      `json:"login"`
	DisplayName pgtype.Text `json:"display_name"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	Email       pgtype.Text `json:"email"`
	// Aggregated embedding (1536-dim) over the developer's past PR titles, finding descriptions, and fix suggestions. Enables the RAG query: "find similar past errors by this author" to inject into the system prompt before LLM inference.
	ExpertiseVector pgvector.Vector    `json:"expertise_vector"`
	TotalPrs        int32              `json:"total_prs"`
	TotalFindings   int32              `json:"total_findings"`
	AvgQualityScore pgtype.Float4      `json:"avg_quality_score"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

// Aggregated developer stats per repository for RAG context.
type DeveloperRepositoryStat struct {
	ID                 int64         `json:"id"`
	DeveloperID        int64         `json:"developer_id"`
	RepositoryID       int64         `json:"repository_id"`
	OrganizationID     int64         `json:"organization_id"`
	TotalPrs           int32         `json:"total_prs"`
	TotalFindings      int32         `json:"total_findings"`
	FindingsCritical   int32         `json:"findings_critical"`
	FindingsHigh       int32         `json:"findings_high"`
	AvgQualityScore    pgtype.Float4 `json:"avg_quality_score"`
	AvgAnalysisSeconds pgtype.Float4 `json:"avg_analysis_seconds"`
	// Top finding categories for this developer in this repo. Example: {'Security', 'Complexity'}. Injected into the system prompt so the LLM focuses its analysis on the developer's known weak areas.
	RecurringCategories []string           `json:"recurring_categories"`
	FirstPrAt           pgtype.Timestamptz `json:"first_pr_at"`
	LastPrAt            pgtype.Timestamptz `json:"last_pr_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
}

// Pre-aggregated DORA metrics for sub-5ms dashboard queries.
type DoraDailyRollup struct {
	ID   int64       `json:"id"`
	Date pgtype.Date `json:"date"`
	// NULL for organization-level aggregate rows. Allows a single table to serve both per-repository and per-organization dashboard views.
	RepositoryID     pgtype.Int8 `json:"repository_id"`
	OrganizationID   int64       `json:"organization_id"`
	DeploymentsCount int32       `json:"deployments_count"`
	// Median Lead Time for Changes: time from first commit on the branch to PR merge, in minutes. The DORA elite benchmark is < 24 hours (< 1440 minutes).
	LeadTimeP50Mins pgtype.Float4 `json:"lead_time_p50_mins"`
	LeadTimeP95Mins pgtype.Float4 `json:"lead_time_p95_mins"`
	LeadTimeP99Mins pgtype.Float4 `json:"lead_time_p99_mins"`
	PrsMerged       int32         `json:"prs_merged"`
	// Count of PRs merged on this date that were subsequently reverted within 48 hours. change_failure_rate = prs_reverted / NULLIF(prs_merged, 0). DORA elite benchmark: < 5%.
	PrsReverted        int32              `json:"prs_reverted"`
	MttrP50Mins        pgtype.Float4      `json:"mttr_p50_mins"`
	MttrP95Mins        pgtype.Float4      `json:"mttr_p95_mins"`
	AvgQualityScore    pgtype.Float4      `json:"avg_quality_score"`
	MinQualityScore    pgtype.Int4        `json:"min_quality_score"`
	MaxQualityScore    pgtype.Int4        `json:"max_quality_score"`
	PrsBlocked         int32              `json:"prs_blocked"`
	PrsPassed          int32              `json:"prs_passed"`
	FindingsCritical   int32              `json:"findings_critical"`
	FindingsHigh       int32              `json:"findings_high"`
	FindingsMedium     int32              `json:"findings_medium"`
	FindingsLow        int32              `json:"findings_low"`
	FindingsInfo       int32              `json:"findings_info"`
	FindingsSuppressed int32              `json:"findings_suppressed"`
	TotalPrsAnalyzed   int32              `json:"total_prs_analyzed"`
	AvgAnalysisMs      pgtype.Float4      `json:"avg_analysis_ms"`
	TotalInputTokens   int64              `json:"total_input_tokens"`
	TotalOutputTokens  int64              `json:"total_output_tokens"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

// Cached GitHub App installation tokens (1h TTL).
type InstallationToken struct {
	ID             int64 `json:"id"`
	InstallationID int64 `json:"installation_id"`
	// GitHub Installation token. In production, encrypted with pgcrypto using a KMS-managed symmetric key before INSERT.
	TokenEncrypted string             `json:"token_encrypted"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

// GitHub organizations/users with an active Sentra App installation.
type Organization struct {
	ID          int64       `json:"id"`
	GithubID    int64       `json:"github_id"`
	Login       string      `json:"login"`
	DisplayName pgtype.Text `json:"display_name"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	Type        string      `json:"type"`
	// GitHub App Installation ID — used to exchange a JWT for a short-lived installation token.
	InstallationID int64  `json:"installation_id"`
	PlanTier       string `json:"plan_tier"`
	IsActive       bool   `json:"is_active"`
	// Organization-wide default Quality Score threshold (0-100). PRs below this score receive conclusion=failure from the Check Runs API, blocking the Merge button. Overridable per repository in repository_policies.
	QualityGateThreshold int32              `json:"quality_gate_threshold"`
	WorkspaceType        string             `json:"workspace_type"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

// M2M: developers belonging to an organization.
type OrganizationMember struct {
	OrganizationID int64              `json:"organization_id"`
	DeveloperID    int64              `json:"developer_id"`
	Role           string             `json:"role"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

// Active subscription for each organization.
type OrganizationSubscription struct {
	ID                    int64              `json:"id"`
	OrganizationID        int64              `json:"organization_id"`
	PlanID                int64              `json:"plan_id"`
	Status                string             `json:"status"`
	CurrentPeriodStart    pgtype.Timestamptz `json:"current_period_start"`
	CurrentPeriodEnd      pgtype.Timestamptz `json:"current_period_end"`
	CancelAt              pgtype.Timestamptz `json:"cancel_at"`
	CanceledAt            pgtype.Timestamptz `json:"canceled_at"`
	PrsAnalyzedThisPeriod int32              `json:"prs_analyzed_this_period"`
	StripeSubscriptionID  pgtype.Text        `json:"stripe_subscription_id"`
	StripeCustomerID      pgtype.Text        `json:"stripe_customer_id"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

// Transactional Outbox for at-least-once Kafka delivery.
type OutboxEvent struct {
	ID int64 `json:"id"`
	// Kafka partition key: "{repository_id}:{pull_request_number}". Kafka murmur2 hash of this key maps every event for a given PR to the SAME partition, ensuring the Python AI Worker processes them in strict chronological order.
	AggregateID string `json:"aggregate_id"`
	EventType   string `json:"event_type"`
	KafkaTopic  string `json:"kafka_topic"`
	// Binary Protobuf bytes. Schema defined in packages/contracts/proto/sentra/v1/events.proto. Never re-serialize to JSON before publishing — byte-level fidelity is required for HMAC integrity and schema registry compatibility.
	PayloadProto []byte             `json:"payload_proto"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	PublishedAt  pgtype.Timestamptz `json:"published_at"`
	RetryCount   int32              `json:"retry_count"`
	LastError    pgtype.Text        `json:"last_error"`
}

// Files changed within a pull request.
type PrFile struct {
	ID            int64  `json:"id"`
	PullRequestID int64  `json:"pull_request_id"`
	Filename      string `json:"filename"`
	Status        string `json:"status"`
	Additions     int32  `json:"additions"`
	Deletions     int32  `json:"deletions"`
	// Raw unified diff for this file after Context Pruning (lock files stripped, git metadata headers removed). Stored to enable analysis retry without re-fetching from the GitHub API (avoids hitting rate limits on retry).
	Patch            pgtype.Text `json:"patch"`
	PreviousFilename pgtype.Text `json:"previous_filename"`
	WasExcluded      bool        `json:"was_excluded"`
	ExclusionReason  pgtype.Text `json:"exclusion_reason"`
}

// Central entity: one row per analyzed GitHub PR.
type PullRequest struct {
	ID             int64       `json:"id"`
	GithubPrID     int64       `json:"github_pr_id"`
	RepositoryID   int64       `json:"repository_id"`
	OrganizationID int64       `json:"organization_id"`
	PullNumber     int32       `json:"pull_number"`
	Title          string      `json:"title"`
	Body           pgtype.Text `json:"body"`
	AuthorID       pgtype.Int8 `json:"author_id"`
	AuthorLogin    string      `json:"author_login"`
	BaseBranch     string      `json:"base_branch"`
	HeadBranch     string      `json:"head_branch"`
	// The commit SHA at the HEAD of the PR branch at the time of analysis. Used as the Kafka partition key (with pull_number) and as the GitHub Check Run 'head_sha'.
	HeadSha        string             `json:"head_sha"`
	BaseSha        string             `json:"base_sha"`
	State          string             `json:"state"`
	IsDraft        bool               `json:"is_draft"`
	MergedAt       pgtype.Timestamptz `json:"merged_at"`
	ClosedAt       pgtype.Timestamptz `json:"closed_at"`
	AnalysisStatus string             `json:"analysis_status"`
	// Final Quality Score (0-100). Computed as QS = 100 - Σ w(sᵢ) where w(CRITICAL)=25, w(HIGH)=15, w(MEDIUM)=5, w(LOW)=1, w(INFO)=0. Clamped to 0 minimum. NULL until analysis_status = 'completed'.
	QualityScore pgtype.Int4 `json:"quality_score"`
	// TRUE when check_run_conclusion = 'failure'. This denormalized flag enables fast dashboard queries like "show me all blocked PRs in the last 7 days" without joining.
	MergeBlocked        bool               `json:"merge_blocked"`
	CheckRunID          pgtype.Int8        `json:"check_run_id"`
	CheckRunUrl         pgtype.Text        `json:"check_run_url"`
	CheckRunConclusion  pgtype.Text        `json:"check_run_conclusion"`
	AnalysisStartedAt   pgtype.Timestamptz `json:"analysis_started_at"`
	AnalysisCompletedAt pgtype.Timestamptz `json:"analysis_completed_at"`
	// Wall-clock time from analysis_started_at to analysis_completed_at in milliseconds. Stored denormalized because EXTRACT(epoch) calculations on TIMESTAMPTZ in GROUP BY are expensive at dashboard query scale.
	AnalysisDurationMs pgtype.Int4        `json:"analysis_duration_ms"`
	Additions          int32              `json:"additions"`
	Deletions          int32              `json:"deletions"`
	ChangedFiles       int32              `json:"changed_files"`
	FindingsCritical   int32              `json:"findings_critical"`
	FindingsHigh       int32              `json:"findings_high"`
	FindingsMedium     int32              `json:"findings_medium"`
	FindingsLow        int32              `json:"findings_low"`
	FindingsInfo       int32              `json:"findings_info"`
	ModelID            pgtype.Text        `json:"model_id"`
	TotalInputTokens   pgtype.Int4        `json:"total_input_tokens"`
	TotalOutputTokens  pgtype.Int4        `json:"total_output_tokens"`
	GithubCreatedAt    pgtype.Timestamptz `json:"github_created_at"`
	GithubUpdatedAt    pgtype.Timestamptz `json:"github_updated_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

// GitHub repositories that have Sentra analysis enabled.
type Repository struct {
	ID             int64  `json:"id"`
	GithubID       int64  `json:"github_id"`
	OrganizationID int64  `json:"organization_id"`
	Name           string `json:"name"`
	// Composite GitHub identifier "{owner}/{repo}" — unique across all of GitHub. Used as the primary reference in GitHub API calls.
	FullName        string      `json:"full_name"`
	Description     pgtype.Text `json:"description"`
	DefaultBranch   string      `json:"default_branch"`
	PrimaryLanguage pgtype.Text `json:"primary_language"`
	IsPrivate       bool        `json:"is_private"`
	// When FALSE, webhook events are accepted but immediately dropped after the 202 response. Allows pausing analysis without removing the GitHub App installation.
	IsActive         bool               `json:"is_active"`
	AnalysisEnabled  bool               `json:"analysis_enabled"`
	AvgQualityScore  pgtype.Float4      `json:"avg_quality_score"`
	TotalPrsAnalyzed int32              `json:"total_prs_analyzed"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

// Per-repo or org-level analysis configuration.
type RepositoryPolicy struct {
	ID                   int64       `json:"id"`
	RepositoryID         pgtype.Int8 `json:"repository_id"`
	OrganizationID       int64       `json:"organization_id"`
	QualityGateThreshold int32       `json:"quality_gate_threshold"`
	BlockOnCritical      bool        `json:"block_on_critical"`
	EnabledCategories    []string    `json:"enabled_categories"`
	// Glob patterns for files to exclude from analysis entirely. Example: {'tests/**', 'vendor/**', '*.generated.go'}
	IgnorePaths []string `json:"ignore_paths"`
	// Free-text rules injected verbatim into the <organization_rules> XML tag in the LLM system prompt. Example: "Never approve use of eval() in production paths."
	CustomRulesText  pgtype.Text        `json:"custom_rules_text"`
	MaxFindingsPerPr int32              `json:"max_findings_per_pr"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

// Individual AI-discovered code issues with RAG embeddings.
type ReviewFinding struct {
	ID             int64       `json:"id"`
	PullRequestID  int64       `json:"pull_request_id"`
	RepositoryID   int64       `json:"repository_id"`
	OrganizationID int64       `json:"organization_id"`
	FilePath       string      `json:"file_path"`
	LineStart      int32       `json:"line_start"`
	LineEnd        int32       `json:"line_end"`
	Category       string      `json:"category"`
	Severity       string      `json:"severity"`
	Title          string      `json:"title"`
	Description    string      `json:"description"`
	SuggestedFix   pgtype.Text `json:"suggested_fix"`
	RawDetails     pgtype.Text `json:"raw_details"`
	// SHA256 hash of (file_path + line_start + rule_id + code_snippet). Used to match against security_suppression_rules. If a matching suppression rule exists, this finding is soft-deleted (is_suppressed=TRUE) and excluded from the Quality Score calculation and GitHub annotation batch.
	Fingerprint       string             `json:"fingerprint"`
	IsSuppressed      bool               `json:"is_suppressed"`
	SuppressedAt      pgtype.Timestamptz `json:"suppressed_at"`
	SuppressedBy      pgtype.Int8        `json:"suppressed_by"`
	SuppressionReason pgtype.Text        `json:"suppression_reason"`
	// Denormalized penalty weight derived from severity. Stored directly to enable fast SUM(score_weight) GROUP BY pull_request_id without a CASE expression. Quality Score = 100 - SUM(score_weight) WHERE is_suppressed = FALSE.
	ScoreWeight int32 `json:"score_weight"`
	// Dense vector embedding (1536-dim) of the concatenated title + description + suggested_fix. Used by the RAG pipeline in the next analysis for the same developer/repository to retrieve similar historical findings as few-shot examples.
	Embedding    pgvector.Vector    `json:"embedding"`
	DetectorType string             `json:"detector_type"`
	ModelID      pgtype.Text        `json:"model_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

// Persistent fingerprint suppressions for false positives.
type SecuritySuppressionRule struct {
	ID             int64       `json:"id"`
	RepositoryID   pgtype.Int8 `json:"repository_id"`
	OrganizationID int64       `json:"organization_id"`
	// Must exactly match the fingerprint on review_findings. Algorithm: encode(digest(file_path || ':' || line_start || ':' || code_snippet, 'sha256'), 'hex')
	Fingerprint     string      `json:"fingerprint"`
	Reason          string      `json:"reason"`
	Category        string      `json:"category"`
	Severity        string      `json:"severity"`
	SuppressedBy    pgtype.Int8 `json:"suppressed_by"`
	ReviewFindingID pgtype.Int8 `json:"review_finding_id"`
	// NULL = permanent suppression. Set a date for 'risk_accepted' suppressions that should be re-evaluated. The dashboard shows a warning 30 days before expiry.
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Billing plan catalog (free, pro, enterprise).
type SubscriptionPlan struct {
	ID               int64              `json:"id"`
	Name             string             `json:"name"`
	DisplayName      string             `json:"display_name"`
	MaxRepositories  pgtype.Int4        `json:"max_repositories"`
	MaxPrsPerMonth   pgtype.Int4        `json:"max_prs_per_month"`
	MaxDevelopers    pgtype.Int4        `json:"max_developers"`
	PriceUsdPerMonth pgtype.Numeric     `json:"price_usd_per_month"`
	Features         []byte             `json:"features"`
	IsActive         bool               `json:"is_active"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

// GitHub Teams within an organization. Policies and DORA metrics can be scoped to a team.
type Team struct {
	ID             int64              `json:"id"`
	GithubID       int64              `json:"github_id"`
	OrganizationID int64              `json:"organization_id"`
	Name           string             `json:"name"`
	Slug           string             `json:"slug"`
	Description    pgtype.Text        `json:"description"`
	Privacy        string             `json:"privacy"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// M2M: developers within a team.
type TeamMember struct {
	TeamID      int64              `json:"team_id"`
	DeveloperID int64              `json:"developer_id"`
	Role        string             `json:"role"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

// M2M: repositories managed by a team.
type TeamRepository struct {
	TeamID       int64  `json:"team_id"`
	RepositoryID int64  `json:"repository_id"`
	Permission   string `json:"permission"`
}

// Sentra SaaS users authenticated via GitHub OAuth. installation_id is NULL until the user installs the GitHub App on at least one repository.
type User struct {
	ID                int64       `json:"id"`
	GithubID          int64       `json:"github_id"`
	Login             string      `json:"login"`
	Name              pgtype.Text `json:"name"`
	Email             pgtype.Text `json:"email"`
	AvatarUrl         pgtype.Text `json:"avatar_url"`
	GithubAccessToken pgtype.Text `json:"github_access_token"`
	// GitHub App Installation ID for this user. NULL = App not yet installed. Used to associate incoming webhook events with a specific dashboard user.
	InstallationID pgtype.Int8        `json:"installation_id"`
	CurrentOrgID   pgtype.Int8        `json:"current_org_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

// Immutable audit log of all received GitHub webhooks.
type WebhookPayload struct {
	ID int64 `json:"id"`
	// X-GitHub-Delivery UUID. Used as the Redis SETNX key for deduplication (TTL = 86400s). If this UUID is already in Redis, the event is a duplicate and is dropped.
	DeliveryID     pgtype.UUID `json:"delivery_id"`
	EventType      string      `json:"event_type"`
	Action         pgtype.Text `json:"action"`
	InstallationID int64       `json:"installation_id"`
	OrganizationID pgtype.Int8 `json:"organization_id"`
	RepositoryID   pgtype.Int8 `json:"repository_id"`
	SenderLogin    pgtype.Text `json:"sender_login"`
	// Full decoded JSON body of the webhook. GIN-indexed for fast ad-hoc queries. Stored here to enable replay: if the Kafka topic is corrupted or retention expires, the outbox relay can re-publish from these raw payloads.
	Payload        []byte             `json:"payload"`
	SignatureValid bool               `json:"signature_valid"`
	ReceivedAt     pgtype.Timestamptz `json:"received_at"`
	ProcessedAt    pgtype.Timestamptz `json:"processed_at"`
}

// =============================================================================
// B2B Multi-Tenancy Models (Phase: B2B SaaS Pivot)
// =============================================================================

// M2M: users within an organization workspace.
type OrganizationUser struct {
	OrgID    int64              `json:"org_id"`
	UserID   int64              `json:"user_id"`
	Role     string             `json:"role"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

// Organization invitations sent to developers.
type OrganizationInvite struct {
	ID                int64              `json:"id"`
	OrgID             int64              `json:"org_id"`
	InviterID         int64              `json:"inviter_id"`
	TargetEmail       string             `json:"target_email"`
	TargetGithubLogin pgtype.Text        `json:"target_github_login"`
	Status            string             `json:"status"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}
