// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	// Fetches a batch of pending events for the Kafka Relay Worker and locks them.
	// Uses SKIP LOCKED to allow multiple worker goroutines/pods to poll concurrently
	// without blocking each other or double-processing messages.
	// Research1 §2.3: Transactional Outbox pattern.
	GetAndLockPendingOutboxEvents(ctx context.Context, limit int32) ([]GetAndLockPendingOutboxEventsRow, error)
	// Computes aggregate metrics from the rollup table.
	GetOrganizationMetrics(ctx context.Context) (GetOrganizationMetricsRow, error)
	// Fetches a single Pull Request by its ID.
	GetPullRequestByID(ctx context.Context, id int64) (GetPullRequestByIDRow, error)
	// Fetches the most recent PRs across all repositories for the organization.
	GetRecentPullRequests(ctx context.Context, limit int32) ([]GetRecentPullRequestsRow, error)
	// Fetches all repositories for the organization.
	GetRepositories(ctx context.Context) ([]GetRepositoriesRow, error)
	// Fetches all review findings for a specific pull request.
	GetReviewFindingsForPR(ctx context.Context, pullRequestID int64) ([]GetReviewFindingsForPRRow, error)
	// Fetches a user by their GitHub numeric ID.
	GetUserByGitHubID(ctx context.Context, githubID int64) (User, error)
	// Fetches a user by their internal Sentra DB ID (used after JWT validation).
	GetUserByID(ctx context.Context, id int64) (User, error)
	// Inserts a pending message for Kafka delivery.
	// Part 2 of the Transactional Outbox. Must be run in the same db.Tx as InsertWebhookPayload.
	InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) (OutboxEvent, error)
	// =============================================================================
	// Sentra API Gateway — sqlc Queries
	// =============================================================================
	// These raw SQL queries are compiled by sqlc into type-safe Go functions.
	// We use this for the hot webhook ingestion path where ORM overhead is unacceptable.
	// =============================================================================
	// Inserts the raw GitHub webhook payload into the immutable audit log.
	// Part 1 of the Transactional Outbox.
	InsertWebhookPayload(ctx context.Context, arg InsertWebhookPayloadParams) (WebhookPayload, error)
	// Increments retry count and sets error details. If retries exceed limit, status becomes 'failed'.
	MarkOutboxEventFailed(ctx context.Context, arg MarkOutboxEventFailedParams) error
	// Marks an outbox event as successfully published to Kafka.
	MarkOutboxEventPublished(ctx context.Context, id int64) error
	// Updates the installation_id for a user when they install the GitHub App.
	SetUserInstallationID(ctx context.Context, arg SetUserInstallationIDParams) error
	// =============================================================================
	// Dashboard Queries (Phase 12)
	// =============================================================================
	// Ensures the organization exists before inserting dependent records.
	UpsertOrganization(ctx context.Context, arg UpsertOrganizationParams) (int64, error)
	// Ensures the repository exists before inserting dependent records.
	UpsertRepository(ctx context.Context, arg UpsertRepositoryParams) (int64, error)
	// =============================================================================
	// User Authentication Queries (Phase 11: GitHub OAuth)
	// =============================================================================
	// Creates or updates a user based on their GitHub ID (upsert on conflict).
	// Returns the full user row after insert/update.
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
