// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAndLockPendingOutboxEvents = `-- name: GetAndLockPendingOutboxEvents :many
SELECT
    id,
    aggregate_id,
    event_type,
    kafka_topic,
    payload_proto,
    status,
    created_at,
    retry_count
FROM outbox_events
WHERE status = 'pending'
ORDER BY created_at ASC
LIMIT $1
FOR UPDATE SKIP LOCKED
`

type GetAndLockPendingOutboxEventsRow struct {
	ID           int64              `json:"id"`
	AggregateID  string             `json:"aggregate_id"`
	EventType    string             `json:"event_type"`
	KafkaTopic   string             `json:"kafka_topic"`
	PayloadProto []byte             `json:"payload_proto"`
	Status       string             `json:"status"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	RetryCount   int32              `json:"retry_count"`
}

// Fetches a batch of pending events for the Kafka Relay Worker and locks them.
// Uses SKIP LOCKED to allow multiple worker goroutines/pods to poll concurrently
// without blocking each other or double-processing messages.
// Research1 §2.3: Transactional Outbox pattern.
func (q *Queries) GetAndLockPendingOutboxEvents(ctx context.Context, limit int32) ([]GetAndLockPendingOutboxEventsRow, error) {
	rows, err := q.db.Query(ctx, getAndLockPendingOutboxEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAndLockPendingOutboxEventsRow
	for rows.Next() {
		var i GetAndLockPendingOutboxEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.AggregateID,
			&i.EventType,
			&i.KafkaTopic,
			&i.PayloadProto,
			&i.Status,
			&i.CreatedAt,
			&i.RetryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrganizationMetrics = `-- name: GetOrganizationMetrics :one
SELECT
    COALESCE(SUM(deployments_count), 0)::int AS total_deployments,
    COALESCE(SUM(prs_merged), 0)::int AS total_prs_merged,
    COALESCE(SUM(prs_reverted), 0)::int AS total_prs_reverted,
    COALESCE(AVG(avg_quality_score), 0)::float AS average_quality_score,
    COALESCE(SUM(prs_blocked), 0)::int AS total_prs_blocked
FROM dora_daily_rollup
WHERE date >= NOW() - INTERVAL '30 days'
`

type GetOrganizationMetricsRow struct {
	TotalDeployments    int32   `json:"total_deployments"`
	TotalPrsMerged      int32   `json:"total_prs_merged"`
	TotalPrsReverted    int32   `json:"total_prs_reverted"`
	AverageQualityScore float64 `json:"average_quality_score"`
	TotalPrsBlocked     int32   `json:"total_prs_blocked"`
}

// Computes aggregate metrics from the rollup table.
func (q *Queries) GetOrganizationMetrics(ctx context.Context) (GetOrganizationMetricsRow, error) {
	row := q.db.QueryRow(ctx, getOrganizationMetrics)
	var i GetOrganizationMetricsRow
	err := row.Scan(
		&i.TotalDeployments,
		&i.TotalPrsMerged,
		&i.TotalPrsReverted,
		&i.AverageQualityScore,
		&i.TotalPrsBlocked,
	)
	return i, err
}

const getPullRequestByID = `-- name: GetPullRequestByID :one
SELECT
    pr.id,
    pr.github_pr_id,
    pr.pull_number,
    pr.title,
    pr.body,
    pr.author_login,
    pr.state,
    pr.merged_at,
    pr.analysis_status,
    pr.quality_score,
    pr.findings_critical,
    pr.findings_high,
    pr.findings_medium,
    pr.findings_low,
    pr.findings_info,
    pr.created_at,
    r.full_name AS repository_full_name
FROM pull_requests pr
JOIN repositories r ON pr.repository_id = r.id
WHERE pr.id = $1
LIMIT 1
`

type GetPullRequestByIDRow struct {
	ID                 int64              `json:"id"`
	GithubPrID         int64              `json:"github_pr_id"`
	PullNumber         int32              `json:"pull_number"`
	Title              string             `json:"title"`
	Body               pgtype.Text        `json:"body"`
	AuthorLogin        string             `json:"author_login"`
	State              string             `json:"state"`
	MergedAt           pgtype.Timestamptz `json:"merged_at"`
	AnalysisStatus     string             `json:"analysis_status"`
	QualityScore       pgtype.Int4        `json:"quality_score"`
	FindingsCritical   int32              `json:"findings_critical"`
	FindingsHigh       int32              `json:"findings_high"`
	FindingsMedium     int32              `json:"findings_medium"`
	FindingsLow        int32              `json:"findings_low"`
	FindingsInfo       int32              `json:"findings_info"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	RepositoryFullName string             `json:"repository_full_name"`
}

// Fetches a single Pull Request by its ID.
func (q *Queries) GetPullRequestByID(ctx context.Context, id int64) (GetPullRequestByIDRow, error) {
	row := q.db.QueryRow(ctx, getPullRequestByID, id)
	var i GetPullRequestByIDRow
	err := row.Scan(
		&i.ID,
		&i.GithubPrID,
		&i.PullNumber,
		&i.Title,
		&i.Body,
		&i.AuthorLogin,
		&i.State,
		&i.MergedAt,
		&i.AnalysisStatus,
		&i.QualityScore,
		&i.FindingsCritical,
		&i.FindingsHigh,
		&i.FindingsMedium,
		&i.FindingsLow,
		&i.FindingsInfo,
		&i.CreatedAt,
		&i.RepositoryFullName,
	)
	return i, err
}

const getRecentPullRequests = `-- name: GetRecentPullRequests :many
SELECT
    pr.id,
    pr.title,
    pr.pull_number,
    pr.author_login,
    pr.state,
    pr.merged_at,
    pr.analysis_status,
    pr.quality_score,
    pr.merge_blocked,
    pr.findings_critical,
    pr.findings_high,
    pr.findings_medium,
    pr.findings_low,
    pr.findings_info,
    pr.created_at,
    r.full_name AS repository_full_name
FROM pull_requests pr
JOIN repositories r ON pr.repository_id = r.id
ORDER BY pr.created_at DESC
LIMIT $1
`

type GetRecentPullRequestsRow struct {
	ID                 int64              `json:"id"`
	Title              string             `json:"title"`
	PullNumber         int32              `json:"pull_number"`
	AuthorLogin        string             `json:"author_login"`
	State              string             `json:"state"`
	MergedAt           pgtype.Timestamptz `json:"merged_at"`
	AnalysisStatus     string             `json:"analysis_status"`
	QualityScore       pgtype.Int4        `json:"quality_score"`
	MergeBlocked       bool               `json:"merge_blocked"`
	FindingsCritical   int32              `json:"findings_critical"`
	FindingsHigh       int32              `json:"findings_high"`
	FindingsMedium     int32              `json:"findings_medium"`
	FindingsLow        int32              `json:"findings_low"`
	FindingsInfo       int32              `json:"findings_info"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	RepositoryFullName string             `json:"repository_full_name"`
}

// Fetches the most recent PRs across all repositories for the organization.
func (q *Queries) GetRecentPullRequests(ctx context.Context, limit int32) ([]GetRecentPullRequestsRow, error) {
	rows, err := q.db.Query(ctx, getRecentPullRequests, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentPullRequestsRow
	for rows.Next() {
		var i GetRecentPullRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.PullNumber,
			&i.AuthorLogin,
			&i.State,
			&i.MergedAt,
			&i.AnalysisStatus,
			&i.QualityScore,
			&i.MergeBlocked,
			&i.FindingsCritical,
			&i.FindingsHigh,
			&i.FindingsMedium,
			&i.FindingsLow,
			&i.FindingsInfo,
			&i.CreatedAt,
			&i.RepositoryFullName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRepositories = `-- name: GetRepositories :many
SELECT
    id,
    github_id,
    organization_id,
    name,
    full_name,
    is_private,
    is_active,
    analysis_enabled,
    avg_quality_score,
    total_prs_analyzed,
    created_at
FROM repositories
ORDER BY full_name ASC
`

type GetRepositoriesRow struct {
	ID               int64              `json:"id"`
	GithubID         int64              `json:"github_id"`
	OrganizationID   int64              `json:"organization_id"`
	Name             string             `json:"name"`
	FullName         string             `json:"full_name"`
	IsPrivate        bool               `json:"is_private"`
	IsActive         bool               `json:"is_active"`
	AnalysisEnabled  bool               `json:"analysis_enabled"`
	AvgQualityScore  pgtype.Float4      `json:"avg_quality_score"`
	TotalPrsAnalyzed int32              `json:"total_prs_analyzed"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

// Fetches all repositories for the organization.
func (q *Queries) GetRepositories(ctx context.Context) ([]GetRepositoriesRow, error) {
	rows, err := q.db.Query(ctx, getRepositories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRepositoriesRow
	for rows.Next() {
		var i GetRepositoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.GithubID,
			&i.OrganizationID,
			&i.Name,
			&i.FullName,
			&i.IsPrivate,
			&i.IsActive,
			&i.AnalysisEnabled,
			&i.AvgQualityScore,
			&i.TotalPrsAnalyzed,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReviewFindingsForPR = `-- name: GetReviewFindingsForPR :many
SELECT
    id,
    file_path,
    line_start,
    line_end,
    category,
    severity,
    title,
    description,
    suggested_fix
FROM review_findings
WHERE pull_request_id = $1
ORDER BY line_start ASC
`

type GetReviewFindingsForPRRow struct {
	ID           int64       `json:"id"`
	FilePath     string      `json:"file_path"`
	LineStart    int32       `json:"line_start"`
	LineEnd      int32       `json:"line_end"`
	Category     string      `json:"category"`
	Severity     string      `json:"severity"`
	Title        string      `json:"title"`
	Description  string      `json:"description"`
	SuggestedFix pgtype.Text `json:"suggested_fix"`
}

// Fetches all review findings for a specific pull request.
func (q *Queries) GetReviewFindingsForPR(ctx context.Context, pullRequestID int64) ([]GetReviewFindingsForPRRow, error) {
	rows, err := q.db.Query(ctx, getReviewFindingsForPR, pullRequestID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReviewFindingsForPRRow
	for rows.Next() {
		var i GetReviewFindingsForPRRow
		if err := rows.Scan(
			&i.ID,
			&i.FilePath,
			&i.LineStart,
			&i.LineEnd,
			&i.Category,
			&i.Severity,
			&i.Title,
			&i.Description,
			&i.SuggestedFix,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserByGitHubID = `-- name: GetUserByGitHubID :one
SELECT id, github_id, login, name, email, avatar_url, github_access_token, installation_id, created_at, updated_at FROM users
WHERE github_id = $1
LIMIT 1
`

// Fetches a user by their GitHub numeric ID.
func (q *Queries) GetUserByGitHubID(ctx context.Context, githubID int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByGitHubID, githubID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Login,
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.GithubAccessToken,
		&i.InstallationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, github_id, login, name, email, avatar_url, github_access_token, installation_id, created_at, updated_at FROM users
WHERE id = $1
LIMIT 1
`

// Fetches a user by their internal Sentra DB ID (used after JWT validation).
func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Login,
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.GithubAccessToken,
		&i.InstallationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :one
INSERT INTO outbox_events (
    aggregate_id,
    event_type,
    kafka_topic,
    payload_proto,
    status,
    retry_count
) VALUES (
    $1, $2, $3, $4, 'pending', 0
)
RETURNING id, aggregate_id, event_type, kafka_topic, payload_proto, status, created_at, published_at, retry_count, last_error
`

type InsertOutboxEventParams struct {
	AggregateID  string `json:"aggregate_id"`
	EventType    string `json:"event_type"`
	KafkaTopic   string `json:"kafka_topic"`
	PayloadProto []byte `json:"payload_proto"`
}

// Inserts a pending message for Kafka delivery.
// Part 2 of the Transactional Outbox. Must be run in the same db.Tx as InsertWebhookPayload.
func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) (OutboxEvent, error) {
	row := q.db.QueryRow(ctx, insertOutboxEvent,
		arg.AggregateID,
		arg.EventType,
		arg.KafkaTopic,
		arg.PayloadProto,
	)
	var i OutboxEvent
	err := row.Scan(
		&i.ID,
		&i.AggregateID,
		&i.EventType,
		&i.KafkaTopic,
		&i.PayloadProto,
		&i.Status,
		&i.CreatedAt,
		&i.PublishedAt,
		&i.RetryCount,
		&i.LastError,
	)
	return i, err
}

const insertWebhookPayload = `-- name: InsertWebhookPayload :one

INSERT INTO webhook_payloads (
    delivery_id,
    event_type,
    action,
    installation_id,
    organization_id,
    repository_id,
    sender_login,
    payload,
    signature_valid
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, delivery_id, event_type, action, installation_id, organization_id, repository_id, sender_login, payload, signature_valid, received_at, processed_at
`

type InsertWebhookPayloadParams struct {
	DeliveryID     pgtype.UUID `json:"delivery_id"`
	EventType      string      `json:"event_type"`
	Action         pgtype.Text `json:"action"`
	InstallationID int64       `json:"installation_id"`
	OrganizationID pgtype.Int8 `json:"organization_id"`
	RepositoryID   pgtype.Int8 `json:"repository_id"`
	SenderLogin    pgtype.Text `json:"sender_login"`
	Payload        []byte      `json:"payload"`
	SignatureValid bool        `json:"signature_valid"`
}

// =============================================================================
// Sentra API Gateway — sqlc Queries
// =============================================================================
// These raw SQL queries are compiled by sqlc into type-safe Go functions.
// We use this for the hot webhook ingestion path where ORM overhead is unacceptable.
// =============================================================================
// Inserts the raw GitHub webhook payload into the immutable audit log.
// Part 1 of the Transactional Outbox.
func (q *Queries) InsertWebhookPayload(ctx context.Context, arg InsertWebhookPayloadParams) (WebhookPayload, error) {
	row := q.db.QueryRow(ctx, insertWebhookPayload,
		arg.DeliveryID,
		arg.EventType,
		arg.Action,
		arg.InstallationID,
		arg.OrganizationID,
		arg.RepositoryID,
		arg.SenderLogin,
		arg.Payload,
		arg.SignatureValid,
	)
	var i WebhookPayload
	err := row.Scan(
		&i.ID,
		&i.DeliveryID,
		&i.EventType,
		&i.Action,
		&i.InstallationID,
		&i.OrganizationID,
		&i.RepositoryID,
		&i.SenderLogin,
		&i.Payload,
		&i.SignatureValid,
		&i.ReceivedAt,
		&i.ProcessedAt,
	)
	return i, err
}

const markOutboxEventFailed = `-- name: MarkOutboxEventFailed :exec
UPDATE outbox_events
SET
    retry_count = retry_count + 1,
    last_error = $1::text,
    status = CASE WHEN retry_count + 1 >= $2::int THEN 'failed' ELSE 'pending' END
WHERE id = $3
`

type MarkOutboxEventFailedParams struct {
	LastError  string `json:"last_error"`
	MaxRetries int32  `json:"max_retries"`
	ID         int64  `json:"id"`
}

// Increments retry count and sets error details. If retries exceed limit, status becomes 'failed'.
func (q *Queries) MarkOutboxEventFailed(ctx context.Context, arg MarkOutboxEventFailedParams) error {
	_, err := q.db.Exec(ctx, markOutboxEventFailed, arg.LastError, arg.MaxRetries, arg.ID)
	return err
}

const markOutboxEventPublished = `-- name: MarkOutboxEventPublished :exec
UPDATE outbox_events
SET
    status = 'published',
    published_at = NOW()
WHERE id = $1
`

// Marks an outbox event as successfully published to Kafka.
func (q *Queries) MarkOutboxEventPublished(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markOutboxEventPublished, id)
	return err
}

const setUserInstallationID = `-- name: SetUserInstallationID :exec
UPDATE users
SET
    installation_id = $1,
    updated_at      = NOW()
WHERE github_id = $2
`

type SetUserInstallationIDParams struct {
	InstallationID pgtype.Int8 `json:"installation_id"`
	GithubID       int64       `json:"github_id"`
}

// Updates the installation_id for a user when they install the GitHub App.
func (q *Queries) SetUserInstallationID(ctx context.Context, arg SetUserInstallationIDParams) error {
	_, err := q.db.Exec(ctx, setUserInstallationID, arg.InstallationID, arg.GithubID)
	return err
}

const upsertOrganization = `-- name: UpsertOrganization :one

INSERT INTO organizations (
    github_id, login, type, installation_id, plan_tier, is_active, quality_gate_threshold
) VALUES (
    $1, $2, $3, $4, 'free', true, 80
) ON CONFLICT (github_id) DO UPDATE
SET login = EXCLUDED.login, type = EXCLUDED.type, installation_id = EXCLUDED.installation_id
RETURNING id
`

type UpsertOrganizationParams struct {
	GithubID       int64  `json:"github_id"`
	Login          string `json:"login"`
	Type           string `json:"type"`
	InstallationID int64  `json:"installation_id"`
}

// =============================================================================
// Dashboard Queries (Phase 12)
// =============================================================================
// Ensures the organization exists before inserting dependent records.
func (q *Queries) UpsertOrganization(ctx context.Context, arg UpsertOrganizationParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertOrganization,
		arg.GithubID,
		arg.Login,
		arg.Type,
		arg.InstallationID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertRepository = `-- name: UpsertRepository :one
INSERT INTO repositories (
    github_id, organization_id, full_name, is_private, name, default_branch, is_active, analysis_enabled, total_prs_analyzed
) VALUES (
    $1, $2, $3, $4, split_part($3, '/', 2), 'main', true, true, 0
) ON CONFLICT (github_id) DO UPDATE
SET full_name = EXCLUDED.full_name, is_private = EXCLUDED.is_private
RETURNING id
`

type UpsertRepositoryParams struct {
	GithubID       int64  `json:"github_id"`
	OrganizationID int64  `json:"organization_id"`
	FullName       string `json:"full_name"`
	IsPrivate      bool   `json:"is_private"`
}

// Ensures the repository exists before inserting dependent records.
func (q *Queries) UpsertRepository(ctx context.Context, arg UpsertRepositoryParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertRepository,
		arg.GithubID,
		arg.OrganizationID,
		arg.FullName,
		arg.IsPrivate,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertUser = `-- name: UpsertUser :one

INSERT INTO users (
    github_id,
    login,
    name,
    email,
    avatar_url,
    github_access_token,
    installation_id,
    updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, NOW()
)
ON CONFLICT (github_id) DO UPDATE
SET
    login               = EXCLUDED.login,
    name                = EXCLUDED.name,
    email               = EXCLUDED.email,
    avatar_url          = EXCLUDED.avatar_url,
    github_access_token = EXCLUDED.github_access_token,
    installation_id     = COALESCE(EXCLUDED.installation_id, users.installation_id),
    updated_at          = NOW()
RETURNING id, github_id, login, name, email, avatar_url, github_access_token, installation_id, created_at, updated_at
`

type UpsertUserParams struct {
	GithubID          int64       `json:"github_id"`
	Login             string      `json:"login"`
	Name              pgtype.Text `json:"name"`
	Email             pgtype.Text `json:"email"`
	AvatarUrl         pgtype.Text `json:"avatar_url"`
	GithubAccessToken pgtype.Text `json:"github_access_token"`
	InstallationID    pgtype.Int8 `json:"installation_id"`
}

// =============================================================================
// User Authentication Queries (Phase 11: GitHub OAuth)
// =============================================================================
// Creates or updates a user based on their GitHub ID (upsert on conflict).
// Returns the full user row after insert/update.
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.GithubID,
		arg.Login,
		arg.Name,
		arg.Email,
		arg.AvatarUrl,
		arg.GithubAccessToken,
		arg.InstallationID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.Login,
		&i.Name,
		&i.Email,
		&i.AvatarUrl,
		&i.GithubAccessToken,
		&i.InstallationID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
