import pgvector.sqlalchemy
"""Phase 12 add missing tables

Revision ID: 7cab2d66e2f1
Revises: b8c2d4e6f8a0
Create Date: 2026-07-31 19:39:21.716737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7cab2d66e2f1'
down_revision: Union[str, None] = 'b8c2d4e6f8a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('developers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('github_id', sa.BigInteger(), nullable=False),
    sa.Column('login', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('expertise_vector', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('total_prs', sa.Integer(), nullable=False),
    sa.Column('total_findings', sa.Integer(), nullable=False),
    sa.Column('avg_quality_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('organizations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('github_id', sa.BigInteger(), nullable=False),
    sa.Column('login', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('installation_id', sa.BigInteger(), nullable=False),
    sa.Column('plan_tier', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('quality_gate_threshold', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_id'),
    sa.UniqueConstraint('installation_id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('repositories',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('github_id', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_branch', sa.Text(), nullable=False),
    sa.Column('primary_language', sa.Text(), nullable=True),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('analysis_enabled', sa.Boolean(), nullable=False),
    sa.Column('avg_quality_score', sa.Float(), nullable=True),
    sa.Column('total_prs_analyzed', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('full_name'),
    sa.UniqueConstraint('github_id')
    )
    op.create_table('dora_daily_rollup',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('repository_id', sa.BigInteger(), nullable=True),
    sa.Column('organization_id', sa.BigInteger(), nullable=False),
    sa.Column('deployments_count', sa.Integer(), nullable=False),
    sa.Column('lead_time_p50_mins', sa.Float(), nullable=True),
    sa.Column('lead_time_p95_mins', sa.Float(), nullable=True),
    sa.Column('lead_time_p99_mins', sa.Float(), nullable=True),
    sa.Column('prs_merged', sa.Integer(), nullable=False),
    sa.Column('prs_reverted', sa.Integer(), nullable=False),
    sa.Column('mttr_p50_mins', sa.Float(), nullable=True),
    sa.Column('mttr_p95_mins', sa.Float(), nullable=True),
    sa.Column('avg_quality_score', sa.Float(), nullable=True),
    sa.Column('min_quality_score', sa.Integer(), nullable=True),
    sa.Column('max_quality_score', sa.Integer(), nullable=True),
    sa.Column('prs_blocked', sa.Integer(), nullable=False),
    sa.Column('prs_passed', sa.Integer(), nullable=False),
    sa.Column('findings_critical', sa.Integer(), nullable=False),
    sa.Column('findings_high', sa.Integer(), nullable=False),
    sa.Column('findings_medium', sa.Integer(), nullable=False),
    sa.Column('findings_low', sa.Integer(), nullable=False),
    sa.Column('findings_info', sa.Integer(), nullable=False),
    sa.Column('findings_suppressed', sa.Integer(), nullable=False),
    sa.Column('total_prs_analyzed', sa.Integer(), nullable=False),
    sa.Column('avg_analysis_ms', sa.Float(), nullable=True),
    sa.Column('total_input_tokens', sa.BigInteger(), nullable=False),
    sa.Column('total_output_tokens', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhook_payloads',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('delivery_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('installation_id', sa.BigInteger(), nullable=False),
    sa.Column('organization_id', sa.BigInteger(), nullable=True),
    sa.Column('repository_id', sa.BigInteger(), nullable=True),
    sa.Column('sender_login', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('signature_valid', sa.Boolean(), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repository_id'], ['repositories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_id')
    )
    op.alter_column('outbox_events', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('pull_requests', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('pull_requests', 'github_pr_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('pull_requests', 'repository_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('pull_requests', 'organization_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('pull_requests', 'author_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.alter_column('pull_requests', 'check_run_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.create_foreign_key(None, 'pull_requests', 'repositories', ['repository_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'pull_requests', 'developers', ['author_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'pull_requests', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.alter_column('review_findings', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('review_findings', 'pull_request_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('review_findings', 'repository_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('review_findings', 'organization_id',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('review_findings', 'suppressed_by',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=True)
    op.create_foreign_key(None, 'review_findings', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'review_findings', 'developers', ['suppressed_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'review_findings', 'repositories', ['repository_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('idx_users_github_id'), table_name='users')
    op.drop_index(op.f('idx_users_login'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_login'), 'users', ['login'], unique=True)
    op.create_index(op.f('idx_users_github_id'), 'users', ['github_id'], unique=True)
    op.drop_constraint(None, 'review_findings', type_='foreignkey')
    op.drop_constraint(None, 'review_findings', type_='foreignkey')
    op.drop_constraint(None, 'review_findings', type_='foreignkey')
    op.alter_column('review_findings', 'suppressed_by',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('review_findings', 'organization_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('review_findings', 'repository_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('review_findings', 'pull_request_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('review_findings', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_constraint(None, 'pull_requests', type_='foreignkey')
    op.drop_constraint(None, 'pull_requests', type_='foreignkey')
    op.drop_constraint(None, 'pull_requests', type_='foreignkey')
    op.alter_column('pull_requests', 'check_run_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('pull_requests', 'author_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('pull_requests', 'organization_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('pull_requests', 'repository_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('pull_requests', 'github_pr_id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('pull_requests', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('outbox_events', 'id',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_table('webhook_payloads')
    op.drop_table('dora_daily_rollup')
    op.drop_table('repositories')
    op.drop_table('organizations')
    op.drop_table('developers')
    # ### end Alembic commands ###
